### ISSUE TITLE
what about claims?

### ISSUE THREAD

**Issue by clementAC** [johnf/serverless-cognito-demo#4]
Hi,

I tried to found some details on cognito user pool authentication and it's quite hard. This exemple make the things quite clear but i have a question concerning the claim option. What this option is for? checking the group apartenance of the user?

**Comment by johnf** [comment]
Claims are the attributes on the user e.g. name, email or anything else you add. They are different to groups which I haven't experimented with yet

**Comment by clementAC** [comment]
Ok it's definitively not what I was thinking about =). Thank you for your reply
